In [1]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print (z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
#2：min()、max()函数

In [3]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [4]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print (z)
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print (z)

[[6.08503645 9.37793769 5.73944117 7.89701763 8.62351416]
 [4.89112511 8.89861444 2.73849793 5.80644627 2.01435584]
 [4.37057577 3.67968792 1.98441606 9.50126312 5.9767205 ]
 [7.22852751 8.97814265 6.10114118 4.19988439 5.67238958]
 [1.24511582 7.14554631 3.10231944 5.24206594 0.62487916]]
[[0.61513307 0.98610634 0.57619883 0.81926813 0.90111413]
 [0.48062882 0.93210651 0.2381171  0.58374752 0.15653634]
 [0.42198452 0.34415014 0.15316337 1.         0.60293036]
 [0.74395704 0.94106604 0.6169474  0.40275469 0.56864489]
 [0.06987492 0.73460851 0.27910468 0.52016528 0.        ]]


In [5]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print (np.arange(5))
print (z)


[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [6]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11,endpoint=True,retstep=True)
print (z)


(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [7]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is