In [1]:
import tensorflow as tf

C:\Users\14982\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
# 创建一个随机变量
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]]) 
y = tf.matmul(w, x)  

#初始化
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print (y.eval())

[1 2 3 4 5 6 7]


In [14]:
#创建一个常量
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])
sess = tf.Session()
print(sess.run(tensor))

[1 2 3 4 5 6 7]


In [8]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)#高斯函数  随机创建矩阵

# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)  #洗牌

# Each time we run these ops, different results are generated
sess = tf.Session()
print (sess.run(norm))
print (sess.run(shuff))

[[-4.126405  -0.5808178  4.7420774]
 [ 3.178742  -4.6185637 -7.215119 ]]
[[5 6]
 [1 2]
 [3 4]]


In [7]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value) #把后面的值赋值给前面的值

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))    
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [58]:
#tf.train.Saver
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w, x)
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
# Do some work with the model.
# Save the variables to disk.
    save_path = saver.save(sess, "C://tensorflow//model//test")
    print ("Model saved in file: ", save_path)


Model saved in file:  C://tensorflow//model//test


In [62]:
import numpy as np
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a) #把numpy格式转化成tensorflow支持的格式
with tf.Session() as sess:
     print(sess.run(ta))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [13]:
input1 = tf.placeholder(tf.float32) #在session中获得位置 ,随后在赋值
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))

[array([14.], dtype=float32)]
